### PR TITLE
Implement async behavior

### PR DESCRIPTION
**Pull request by ScreamZ**
Hey @endel, 

I've implemented a first draft. 
I made some assumptions on usage to make the API easier to use. 

I prefer to write
```ts
await clock.duration(2000);
```

then something like (finding a good word is dirty) and people can still use the timeout API if they need specific interruption, which I think is pretty edge-case. Maybe I'm wrong. But tell me what you think to have a simple and clear API.

```ts
await clock.duration(2000).promise
```

I will let you look at the JSdoc associated with Typescript file and example. 
Also, I've added some tests. Updated the libraries and fixed import with `esModuleInterop`.

Please let me know what you think, I'll try to experiment with this a bit in my code before merging.

## Some examples:

**Inside an async function** -> Easy sequencing
```typescript
const timer = new Clock(true);

try {
  await timer.duration(1000);
  console.log("1 second later");
  await timer.duration(1000);
  console.log("2 second later");
  await timer.duration(1000);
  console.log("3 second later");
} catch(e) {
  console.log(e.message);
}
```
**Using the promise**
```typescript
const timer = new Clock(true);
timer.duration(1000)
  .then(() => console.log("1 second later"));
```
**Using the promise with error**
```typescript
const timer = new Clock(true);
timer.duration(1000)
  .then(() => console.log("1 second later"))
  .catch(() => console.log("Timer cleared"));
timer.clear();
```

See ya, and keep up the good work on Colyseus :)

Andréas

PS: I didn't made it, but I could also implement a packing option with https://tsup.egoist.dev/ if you want me to.

- https://github.com/colyseus/timer/issues/23

### CODE REVIEW

**Comment by endel** [comment]
Thank you for the PR @ScreamZ 💙

I think the new `IDelayed` interface and `AsyncDelayed` wouldn't be necessary if we provide the `reject` for `.clear()`, and provide the `resolve` for the regular `Delayed` instance, as follows:

```typescript
    return new Promise((resolve, reject) => {
      const delayed = new Delayed(resolve, [], ms, Type.Async);
      delayed.clear = reject;
      this.delayed.push(delayed);
      return delayed;
    });
```

What do you think? Cheers!

**Comment by ScreamZ** [comment]
It sounds like a plan, but we need a small addition, we need to set `active` to `false` to make it clearable by the clear routine.

Also added undefined to make args `void` for `resolve`

```ts
 return new Promise((resolve, reject) => {
      const delayed = new Delayed(resolve, undefined, ms, Type.Async);
      delayed.clear = () => {
		delayed.active = false
        reject(new TimerClearedError("Timer has been cleared")); // To be able to use instanceof in try / catch
      };
      this.delayed.push(delayed);
    });
```

I am making a PR tomorrow it's 2h30 in France time to sleep 😅

**Comment by ScreamZ** [comment]
Hi @endel,

I think we are done.

- Added changeset with changelog tracking
- Updated various library
- Update tests battery
- Added some JSdoc and examples
- Removed travis because the gamestdio doesn't exists anymore
- Updated README with what I understood of the usage and more context on « how it's cool »

## Remaining question
**I'm just wondering if we should mark some field private and introduce a breaking change in a V2**

like accessing `delayed` should not be allowed. Maybe we can make a second pull request with that, so colyseus can opt-in to the new version at anytime, but I think it would be better to mark a lot of fields private.

----

Ping me if you've any question and when package is released

Thanks

**Comment by ScreamZ** [comment]
ping @endel

**Comment by endel** [comment]
Thank you so much for this @ScreamZ 🎉  Just released a new version with your changes.

Regarding the private fields, I think it's ok if we use the `private` keyword only for TypeScript - but if the user would like to update the internal values for any reason it is nice to still have that option (if we use real #private fields it wouldn't be possible to manipulate them from the outside)

**Pull request merged**
